# Generated by Django 3.1.3 on 2020-12-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_test', '0002_auto_20201202_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='first_name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
